name: Build Docker Images

on:
  push:
    branches: [main]

env:
  REGISTRY: ghcr.io
  IMAGE: ${{ github.repository }}

jobs:
  build-amd64:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build amd64 image
        run: |
          docker build \
            --platform linux/amd64 \
            -t ${{ env.REGISTRY }}/${{ env.IMAGE }}:amd64 \
            --build-arg USER=${{ github.actor }} \
            --build-arg TOKEN=${{ secrets.GITHUB_TOKEN }} \
            .
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE }}:amd64
  build-arm64:
    # runs-on: macos-latest
    runs-on: ubuntu-24.04-arm
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build arm64 image
        run: |
          docker build \
            --platform linux/arm64 \
            -t ${{ env.REGISTRY }}/${{ env.IMAGE }}:arm64 \
            --build-arg USER=${{ github.actor }} \
            --build-arg TOKEN=${{ secrets.GITHUB_TOKEN }} \
            .
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE }}:arm64
  create-manifest:
    needs: [build-amd64, build-arm64]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Create and push manifest
        run: |
          docker buildx imagetools create \
            --tag ${{ env.REGISTRY }}/${{ env.IMAGE }}:latest \
            ${{ env.REGISTRY }}/${{ env.IMAGE }}:amd64 \
            ${{ env.REGISTRY }}/${{ env.IMAGE }}:arm64
